## testcase file for Lettcode problem 128
## author MDomalewski, generated by TypicalUsername-ai's leetcode python repository
## created on: 2022-07-05 20:56:30.668496

## import Structures ##uncomment if the task requires a non-basic data structure
import unittest
from Solutions import problem_128

class Problem_128_test(unittest.TestCase):
    def setUp(self):
        self.solution = problem_128.Solution()

    def test1(self):
        self.assertEqual(self.solution.longestConsecutive([100, 4, 200, 1, 3, 2]), 4, "first basic test")

    def test2(self):
        self.assertEqual(self.solution.longestConsecutive([0,3,7,2,5,8,4,6,0,1]), 9, "first basic test")

    def test3(self):
        self.assertEqual(self.solution.longestConsecutive([1, 0, -1]), 3, "first fail case test")

    def test3(self):
        self.assertEqual(self.solution.longestConsecutive([0,1,2,4,8,5,6,7,9,3,55,88,77,99,999999999]), 10, "memload fail case test")

    def test3(self):
        self.assertEqual(self.solution.longestConsecutive([1,3,5,2,4]), 5, "second fail case test")




st = unittest.defaultTestLoader.loadTestsFromTestCase(Problem_128_test)
unittest.TextTestRunner().run(st)
