## testcase file for Lettcode problem 199
## author MDomalewski, generated by TypicalUsername-ai's leetcode python repository
## created on: 2022-07-11 17:00:55.922602

## import Structures ##uncomment if the task requires a non-basic data structure
import unittest
from Solutions import problem_199

class Problem_199_test(unittest.TestCase):
    def setUp(self):
        self.solution = problem_199.Solution()

    def test_empty(self):
        self.assert_(self.solution.rightSideView(None) == [])

st = unittest.defaultTestLoader.loadTestsFromTestCase(Problem_199_test)
unittest.TextTestRunner().run(st)
