## testcase file for Lettcode problem 695
## author MDomalewski, generated by TypicalUsername-ai's leetcode python repository
## created on: 2022-07-15 12:51:57.220300

## import Structures ##uncomment if the task requires a non-basic data structure
import unittest
from Solutions import problem_695

class Problem_695_test(unittest.TestCase):
    def setUp(self):
        self.solution = problem_695.Solution()

    def test1(self):
        grid = [[0,0,1,0,0,0,0,1,0,0,0,0,0],[0,0,0,0,0,0,0,1,1,1,0,0,0],[0,1,1,0,1,0,0,0,0,0,0,0,0],[0,1,0,0,1,1,0,0,1,0,1,0,0],[0,1,0,0,1,1,0,0,1,1,1,0,0],[0,0,0,0,0,0,0,0,0,0,1,0,0],[0,0,0,0,0,0,0,1,1,1,0,0,0],[0,0,0,0,0,0,0,1,1,0,0,0,0]]
        for r in range(len(grid)):
            print(grid[r])
        self.assertEqual(self.solution.maxAreaOfIsland(grid), 6)
    
    def test2(self):
        grid = [[0,0,0,0,0,0,0,0]]
        for r in range(len(grid)):
            print(grid[r])
        self.assertEqual(self.solution.maxAreaOfIsland(grid), 0)

st = unittest.defaultTestLoader.loadTestsFromTestCase(Problem_695_test)
unittest.TextTestRunner().run(st)
