## testcase file for Lettcode problem 509
## author MDomalewski, generated by TypicalUsername-ai's leetcode python repository
## created on: 2022-07-06 13:05:56.286215

## import Structures ##uncomment if the task requires a non-basic data structure
import unittest
from Solutions import problem_509

class Problem_509_test(unittest.TestCase):
    def setUp(self):
        self.solution = problem_509.Solution()

    def test1(self):
        self.assertEqual(self.solution.fib(2), 1, "f(2) = 1")

    def test2(self):
        self.assertEqual(self.solution.fib(3), 2, "f(3) = 2")

    def test3(self):
        self.assertEqual(self.solution.fib(4), 3, "f(4) = 3")

st = unittest.defaultTestLoader.loadTestsFromTestCase(Problem_509_test)
unittest.TextTestRunner().run(st)
