## testcase file for Lettcode problem 473
## author MDomalewski, generated by TypicalUsername-ai's leetcode python repository
## created on: 2022-07-12 13:08:39.517838

## import Structures ##uncomment if the task requires a non-basic data structure
import unittest
from Solutions import problem_473

class Problem_473_test(unittest.TestCase):
    def setUp(self):
        self.solution = problem_473.Solution()
    # @unittest.skip
    def test_0(self):
        self.assertEqual(self.solution.makesquare([]), False)
    # @unittest.skip
    def test_00(self):
        self.assertEqual(self.solution.makesquare([1,1,2]), False)

    def test_1(self):
        self.assertEqual(self.solution.makesquare([1,1,2,2,2]), True)
    # @unittest.skip
    def test_2(self):
        self.assertEqual(self.solution.makesquare([3,3,3,3,4]), False)
    # @unittest.skip
    def test_3(self):
        self.assertEqual(self.solution.makesquare([5,5,5,5,4,4,4,4,3,3,3,3]), True)


st = unittest.defaultTestLoader.loadTestsFromTestCase(Problem_473_test)
unittest.TextTestRunner().run(st)
