## solution class for Lettcode problem 128
## author MDomalewski, generated by TypicalUsername-ai's leetcode python repository
## created on: 2022-07-05 20:56:30.667496
##import Structures #uncomment if the task requires a non-basic data structure
class Solution(object):
    def longestConsecutive(self, nums):
        """
        :type nums: List[int]
        :rtype: int
        """
        if not nums:
            return 0

        nums.sort()

        longest_streak = 1
        current_streak = 1

        for i in range(1, len(nums)):
            if nums[i] != nums[i-1]:
                if nums[i] == nums[i-1]+1:
                    current_streak += 1
                else:
                    longest_streak = max(longest_streak, current_streak)
                    current_streak = 1

        return max(longest_streak, current_streak)

                


