## solution class for Lettcode problem 509
## author MDomalewski, generated by TypicalUsername-ai's leetcode python repository
## created on: 2022-07-06 13:05:56.285213
##import Structures #uncomment if the task requires a non-basic data structure
class Solution(object):
    def fib(self, n):
        """
        :type n: int
        :rtype: int
        """
        if n <= 1:
            return n
        else:
            return self.fib(n - 1) + self.fib(n - 2)
